services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: oauth
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - oauth-app

  app:
    container_name: oauth-app
    image: oauth-app:latest
    build:
      context: .
      args:
        DATABASE_URL: mysql://root:password@db:3306/oauth
    environment:
      DATABASE_URL: mysql://root:password@db:3306/oauth
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - oauth-app

volumes:
  db_data:

networks:
  oauth-app:
    external: true
