app:
  name: app
  group: app
  replicaCount: 1
  container:
    image: app
    imagePullPolicy: Never
    port: 3000
    config: []
    env:
       - key: key
         value: value
  service:
    type: ClusterIP
    port: 3000