apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
  labels:
    group: {{ .Values.mysql.group }}
spec:
  type: {{ .Values.mysql.service.type }}
  selector:
    app: {{ .Values.mysql.name }}
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.container.port }}
